//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdealProject_Web_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_TheIdealPrtojectEntities : DbContext
    {
        public DB_TheIdealPrtojectEntities()
            : base("name=DB_TheIdealPrtojectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tl_Product> Tl_Product { get; set; }
        public virtual DbSet<Tm_Category> Tm_Category { get; set; }
        public virtual DbSet<Tm_Product> Tm_Product { get; set; }
        public virtual DbSet<Tm_User> Tm_User { get; set; }
    }
}
