//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdealProject_Web_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_TheIdealDatabaseEntities : DbContext
    {
        public DB_TheIdealDatabaseEntities()
            : base("name=DB_TheIdealDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TL_Category> TL_Category { get; set; }
        public virtual DbSet<TL_Product> TL_Product { get; set; }
        public virtual DbSet<TL_SubCategory> TL_SubCategory { get; set; }
        public virtual DbSet<TM_Category> TM_Category { get; set; }
        public virtual DbSet<TM_Product> TM_Product { get; set; }
        public virtual DbSet<TM_SubCategory> TM_SubCategory { get; set; }
        public virtual DbSet<TM_User> TM_User { get; set; }
    }
}
