//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdealProject_Web_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tl_Product
    {
        public long Tl_ProductPk { get; set; }
        public Nullable<long> Product_TmProductFk { get; set; }
        public string productDevelperNote { get; set; }
        public Nullable<bool> productIsActive { get; set; }
        public Nullable<bool> productIsViewable { get; set; }
        public Nullable<bool> productIsDeleted { get; set; }
        public Nullable<long> product_TmCategoryFk { get; set; }
        public string productName { get; set; }
        public Nullable<long> product_TmUserFk_Creator { get; set; }
        public Nullable<System.DateTime> productCreatedAt { get; set; }
        public Nullable<long> product_TmUserFk_Modifier { get; set; }
        public Nullable<System.DateTime> productModifiedAt { get; set; }
        public Nullable<long> productPrice { get; set; }
    }
}
