//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdealProject_Web_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL_SubCategory
    {
        public long TL_SubCategoryPk { get; set; }
        public long TM_SubCategoryFk { get; set; }
        public long TM_CategoryFk { get; set; }
        public long TL_CategoryFk { get; set; }
        public string SubCategory_Name { get; set; }
    }
}
