//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdealProject_Web_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_User
    {
        public long TM_UserPk { get; set; }
        public string User_Name { get; set; }
        public string User_Password { get; set; }
    }
}
